# Generated by Django 6.0 on 2025-12-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_delete_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='typ',
        ),
    ]
